spring.datasource.url=jdbc:postgresql://db:5432/animatch_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Optionnel : Spring Boot 3+ détecte le dialecte automatiquement
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 1. On laisse Hibernate créer/mettre à jour les tables
spring.jpa.hibernate.ddl-auto=update
